# Generated by Django 3.2.9 on 2022-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practo_demo', '0002_auto_20220222_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor_details',
            options={'verbose_name_plural': 'Doctor Detail'},
        ),
        migrations.AlterModelOptions(
            name='user_credential',
            options={'verbose_name_plural': 'User Credential'},
        ),
    ]
